version: 3
images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

dependencies:
  python: requirements.txt
<<<<<<< HEAD

=======
>>>>>>> 507b6f6 (Push working automation project: simulation and patching for AWX)
