version: 3

dependencies:
  python:
    - networkx
    - matplotlib
  system: []
  galaxy: requirements.yml

additional_build_steps:
  prepend_base:
    - RUN pip install ansible-core ansible-runner

