version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:24.1.0

dependencies:
  python: requirements.txt
  system: []
  ansible_core:
    package_pip: ansible-core==2.14.6
  ansible_runner:
    package_pip: ansible-runner

additional_build_steps:
  append_final:
    - COPY . /runner/project/

