---
<<<<<<< HEAD
# Playbook: patch-cves.yml
# Purpose: Install OS packages that remediate the CVEs produced by run_simulation.yml
# Variables:
#   * cve_list - list of CVEs to patch (provided by vars/cves.yml)
#   * patch_map - mapping from CVE to package name(s)
#
# In production, extend patch_map based on vendor advisories.

- name: Apply patches for CVEs on EVCI nodes
=======
- name: Simulate patching CVEs
>>>>>>> 507b6f6 (Push working automation project: simulation and patching for AWX)
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
<<<<<<< HEAD
    - vars/cves.yml

  vars:
    patch_map:
      CVE-2021-22820: "libcurl4"
      CVE-2021-22730: "openssl"
      CVE-2021-22708: "firmware-updater"
      CVE-2022-22808: "lms-server"
      CVE-2021-22818: "libevcharge"

  tasks:
    - name: Refresh package cache
      apt:
        update_cache: yes

    - name: Install packages that fix selected CVEs
      apt:
        name: "{{ patch_map[item] }}"
        state: latest
      loop: "{{ cve_list | intersect(patch_map.keys()) }}"
      loop_control:
        label: "{{ item }} ➔ {{ patch_map[item] }}"

    - name: Log patched CVEs
      lineinfile:
        path: /var/log/patched_cves.log
        create: yes
        line: "Patched CVEs on {{ ansible_date_time.iso8601 }}: {{ cve_list | join(', ') }}"

    - name: Reboot if kernel or critical package updated
      reboot:
        msg: "Reboot initiated by automated patching workflow"
        reboot_timeout: 600
      when: "'linux-image' in ansible_facts.packages"
=======
    - ../vars/cves.yml

  tasks:
    - name: Show patched CVEs
      debug:
        msg: "Simulated patch for CVEs: {{ cve_list }}"

    - name: Save to log
      copy:
        dest: /tmp/patched_cves.log
        content: |
          [{{ ansible_date_time.iso8601 }}] Patched: {{ cve_list | join(', ') }}
>>>>>>> 507b6f6 (Push working automation project: simulation and patching for AWX)
