---
- name: Run attacker simulation and export CVE list
  hosts: localhost
  gather_facts: false
  connection: local

  vars:
    entry_point: "{{ survey_entry_point }}"
    attacker_algo: "{{ survey_attacker_algo }}"
    weighted: "{{ survey_weighted | default('false') }}"

  tasks:
    - name: Install required Python packages
      pip:
        name:
          - networkx
          - matplotlib

    - name: Run attacker simulation
      command: python3 simulation/attacker_al_47.py {{ entry_point }} {{ attacker_algo }} {{ weighted }}
      register: sim_out
      changed_when: false

    - name: Extract CVEs from output
      set_fact:
        cve_list: "{{ sim_out.stdout | regex_findall('CVE-\\\\d{4}-\\\\d{4,}') | unique }}"

    - name: Save CVEs to vars/cves.yml
      copy:
        dest: vars/cves.yml
        content: |
          ---
          cve_list: {{ cve_list | to_nice_yaml(indent=2) }}

    - name: Share CVEs for workflow
      set_stats:
        data:
          patched_cves: "{{ cve_list }}"
